# Generated by Django 6.1.1 on 2026-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
