# Generated by Django 6.1.1 on 2026-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_address_teacherprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
